apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nginx-cache-config
  name: nginx-cache-config
  namespace: cache-dev
data:
  http-snippet: "proxy_cache_path /var/cache/nginx keys_zone=mycache:10m max_size=50m loader_threshold=500 loader_files=300 inactive=2m use_temp_path=off;"