apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: aks-lt-ingress
  namespace: aks-lt-dev
  annotations:    
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/enable-cors: "true"    
spec:
  tls:
  - hosts:
    - "*.internal.wkshpdev.com"
    secretName: aks-lt-tls-secret
  rules:
  - host: loadtest-dev.internal.wkshpdev.com
    http:
      paths:
      - path: /?(.*)
        backend:
          serviceName: nginx-cache-svc
          servicePort: 80