apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-bknd-hpa
  namespace: bkend-dev
spec:
  scaleTargetRef:  
    apiVersion: apps/v1
    kind: Deployment
    name: api-bknd-deploy
  minReplicas: 1
  maxReplicas: 400
  targetCPUUtilizationPercentage: 70