apiVersion: v1
kind: Service
metadata:  
  labels:
    app: api-bknd-svc
  name: api-bknd-svc
  namespace: bkend-dev
spec:  
  ports:
  - port: 7007
    protocol: TCP
    targetPort: 7007
  selector:
    app: api-bknd-pod
  type: LoadBalancer
