apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-proxy-hpa
  namespace: cache-dev
spec:
  scaleTargetRef:  
    apiVersion: apps/v1
    kind: Deployment
    name: api-proxy-deploy
  minReplicas: 1
  maxReplicas: 400
  targetCPUUtilizationPercentage: 70