apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: api-proxy-deploy
  name: api-proxy-deploy
  namespace: cache-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-proxy-pod
  strategy: {}
  template:
    metadata:      
      labels:
        app: api-proxy-pod
    spec:
      containers:
      - image: ngnxacr.azurecr.io/apiproxyapp:v1.0.5
        name: api-proxy-app        
        resources:
         requests:
             cpu: "100m"
             memory: 150Mi
         limits:
             cpu: "200m"
             memory: 300Mi
        env:
        - name: API_URL
          value: http://40.76.150.1:7007
      imagePullSecrets:
          - name: cache-acr-secret

