apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: nginx-cache-deploy
  name: nginx-cache-deploy
  namespace: aks-lt-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-cache-pod
  strategy: {}
  template:
    metadata:      
      labels:
        app: nginx-cache-pod
    spec:
      containers:
      - image: nginx:1.19.0-alpine
        name: nginx-cache-app        
        resources:
         requests:
          cpu: "200m"
          memory: 150Mi
         limits:
          cpu: "400m"
          memory: 300Mi
        volumeMounts:
        - name: nginx-cache-vol
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf        
        ports:
        - containerPort: 80        
      volumes:
      - name: nginx-cache-vol
        configMap:
          name: nginx-cache-config      

